### Show all tasks on to do list
GET http://localhost:1234/todo

### Add new task
POST http://localhost:1234/new-task
Content-Type: application/json

{
    "task": "Create an API server"
}

### Update task: Copy an id from GET and replace "id" in request
PATCH http://localhost:1234/todo/id
Content-Type: application/json

{
    "status": "done"
}

### Delete task: Copy an id from GET and replace "id" in request
DELETE http://localhost:1234/todo/id
